### ISSUE TITLE
クライアントサイドへの自動追加

### ISSUE THREAD

**Issue by CivilTT** [CivilTT/ServerStarter2#58]
# 概要
ServerStarter2で設定したサーバーやMODをクライアントサイドにも自動で追加する機能

自動追加する候補としては下記が考えられる

- 各サーバーのバージョン
- MODやデータパック
- MODサーバー

（その他，サーバーとクライアントの両方に導入が必要なもの）

**Comment by txkodo** [comment]
MODやサーバーの自動追加はおそらく再配布にあたるので、やめておいたほうがいいと思う。
